### ISSUE TITLE
Address CORS policy change in Chrome 59?

### ISSUE THREAD

**Issue by wheeyls** [ankane/ahoy.js#15]
Chrome just changed the way they handle cross-origin `sendBeacon` requests.

https://bugs.chromium.org/p/chromium/issues/detail?id=490015

From what I understand, they don't want cross origin requests to be able to send JSON, but they are allowed to send plaintext. It will be up to the server to deal with the difference in format and deal with the request accordingly.

We got dinged with this in our implementation, because right now we host the JS on our `www` domain, and send CORS requests to our `track` subdomain. Our current plan is to change the way we host the file so that the CORS isn't required, but I'm curious if you think that this is worth updating the library to handle this scenario?

**Comment by ankane** [comment]
Hey @wheeyls, thanks for reporting 👍  This is something we should address in Ahoy, since it shouldn't require CORS.

**Comment by ankane** [comment]
Fixed on master. It'll go out sometime in the next few days with the release of Ahoy.js 1.0.
