### ISSUE TITLE
Post same event multiple times if you have more than one window/tab.

### ISSUE THREAD

**Issue by rddm2bb** [ankane/ahoy.js#16]
If you have a click event trigger ahoy.track, and that click opens a new window or tab, it will post the event twice. I think is because when window/tab loads check for eventQueue and the event is still on eventQueue.
I think the solution is to set the cookie name to ahoy_events_TIMESTAMP. So every window/tab will work on a different cookie.

I found it using ctrl + click on a anchor tag using click event.

**Comment by victorarias** [comment]
Hi!

Is this really an issue? The event id on those events would be the same, so you could de-duplicate them on the backend. Also, by changing this, if the first window (the generated the event) fails the process the event before navigating away, then the event will be lost.

**Comment by ankane** [comment]
Ahoy uses `navigator.sendBeacon` instead of the event queue by default, so this shouldn't be needed.
