### ISSUE TITLE
Integration with segment.io

### ISSUE THREAD

**Issue by Startouf** [ankane/ahoy.js#21]
Hey, do you have tricks/gists to integrate Ahoy.js with Segment.io ?
Is there a way to properly forward visitor ID and event tracking to Ahoy.js ?

I am using Ahoy on my Rails backend and it works great, but with our new React based Frontend we'd like to use some dispatcher service like Segment.io to avoid having to dispatch events everywhere.

**Comment by ankane** [comment]
Hey @Startouf, here's what we did:

1. Added the Ahoy visit token as a property to all Segment events
2. Stopped tracking events through Ahoy (but still track visits)

(I wasn't involved, so don't know the full reasoning)
