### ISSUE TITLE
Unclear how the call to /ahoy/visits works

### ISSUE THREAD

**Issue by nabilfreeman** [ankane/ahoy.js#28]
Hi there, I'm trying to get UTM parameters recorded in Ahoy using this library. They always appear blank, even though `trackView()` stores the full URL correctly in the `visits` table.

I see some information about `landing_page` and how a `POST` to `/ahoy/visits` sends this along with the tracking tokens.

However, watching my Chrome network tab, the only API calls made are to `/ahoy/events`.

Has this behaviour changed, and the README is not up to date?

**Comment by nabilfreeman** [comment]
Ok, I inspected https://github.com/ankane/ahoy.js/blob/ff7a2200af5fb65b68a8e149c8fc0e8188d9b0ca/src/index.js#L262 and now understand the visit recording logic.

I had to also set `startOnReady: false` and then manually start Ahoy with `window.Ahoy.start()`. I'm running it on a Meteor single page app.

**Comment by nabilfreeman** [comment]
My issue is solved, but I'm glad I wrote this out so other people can find it. The readme is a bit "rough and ready"! 😜

**Comment by ankane** [comment]
Hey @nabilfreeman, glad you figured it out. The `page` setting shouldn't affect the `landing_page` variable for visits, which is always set to `window.location.href`. Not sure I understand why `startOnReady: false` needed to be used in your specific situation.
