### ISSUE TITLE
nextjs import issue (solved)

### ISSUE THREAD

**Issue by KohheePeace** [ankane/ahoy.js#35]
Hi @ankane 
Really thanks for your awesome work both client and server.

I use this package with **nextjs** and there was an issue when importing this module.

### *Step to re-create this issue.
1. create next-app by using https://github.com/segmentio/create-next-app
2. import ahoy.js in `pages/index.js`
```js
...
import ahoy from 'ahoy.js'
...
```
It shows error
<img width="802" alt="2019-02-28 22 18 58" src="https://user-images.githubusercontent.com/29557494/53573091-ab3d2880-3ba7-11e9-87c6-bd70bd54c8b4.png">

### *Workaround to solve this issue
**1. dynamic import**
`window is not defined` is well known issue and I tried the well-known solutions.
```js
...
import dynamic from 'next/dynamic'
const ahoy = dynamic(() => import('ahoy.js'), {
  ssr: false
})
```
then, in `componentDidMount` call ahoy method.
```js
...
componentDidMount () {
  ahoy.track('test')
}
```
<img width="1167" alt="2019-02-28 22 29 59" src="https://user-images.githubusercontent.com/29557494/53573433-6f569300-3ba8-11e9-83ed-5f199f9cad52.png">
=> I don't know why this does not work.  
  
  

**2. require module in `componentDidMount`**
 ```js
componentDidMount () {
    this.Ahoy = require('ahoy.js').default
    console.log('Ahoy!', this.Ahoy.track('Hello!'))
  }
```
<img width="1266" alt="2019-02-28 22 35 15" src="https://user-images.githubusercontent.com/29557494/53573773-2f43e000-3ba9-11e9-9623-e91acc409dab.png">

=> This worked. (Post 501 error is not a problem)  

**3. Final Code**
somewhere in project
ex: `utils/customAhoy.js`
```js
import Cookie from 'js-cookie'

const dev = process.env.NODE_ENV !== 'production'
const baseURL = dev ? 'http://api.localhost:3000' : 'https://api.example.com'

const isServer = (typeof window === 'undefined')
let ahoy

if (!isServer) {
  ahoy = require('ahoy.js').default
  ahoy.configure({
    urlPrefix: '',
    visitsUrl: `${baseURL}/ahoy/visits`,
    eventsUrl: `${baseURL}/ahoy/events`,
    page: null,
    platform: 'Web',
    useBeacon: true,
    startOnReady: true,
    trackVisits: true,
    cookies: false,
    cookieDomain: null,
    headers: {'Authorization': `Bearer ${Cookie.get('accessToken')}`},
    visitParams: {},
    withCredentials: true
  })
}

export default ahoy
```
somewhere in project you want to use **ahoy**
ex: `index.js`
```js
import React from 'react'
/* import configured ahoy */
import ahoy from 'utils/customAhoy'

export default class Index extends React.Component {

  componentDidMount () {
    ahoy.trackAll()
  }

  render () {
    return (
      <div />
    )
  }
}
```

I just report this if someone has same trouble and better solutions.

Thanks.

**Comment by ankane** [comment]
Hey @KohheePeace, thanks for following up with the solution 👍

**Comment by firdausmaarof** [comment]
@KohheePeace you are a savior. Thanks.

**Comment by montekaka** [comment]
@kohheepeace  followed the  next.js config, 
in utils/ahoy.js
```
// https://github.com/ankane/ahoy.js/issues/35
import Cookie from 'js-cookie'

const baseURL = process.env.RAILS_ENDPOINT;

const isServer = (typeof window === 'undefined')
let ahoy

if (!isServer) {
  ahoy = require('ahoy.js').default;

  ahoy.configure({
    urlPrefix: '',
    visitsUrl: `${baseURL}/ahoy/visits`,
    eventsUrl: `${baseURL}/ahoy/events`,
    page: "Bio page",
    platform: 'Web',
    useBeacon: true,
    startOnReady: true,
    trackVisits: true,
    cookies: false,
    cookieDomain: null,
    headers: {'Authorization': `Bearer ${Cookie.get('accessToken')}`},
    visitParams: {},
    withCredentials: true
  })
}


export default ahoy
```

but keep getting 
>Access to XMLHttpRequest at 'http://localhost:3000/ahoy/events' from origin 'http://localhost:5000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute. 

in rails ahoy.rb
```
class Ahoy::Store < Ahoy::DatabaseStore
end

# set to true for JavaScript tracking
Ahoy.api = true

# set to true for geocoding
# we recommend configuring local geocoding first
# see https://github.com/ankane/ahoy#geocoding
Ahoy.geocode = true
Ahoy.job_queue = :low_priority

# since the request is from next JS server
# FIXME
Ahoy.track_bots = true
```

Please advise.  
Thanks!

**Comment by kohheepeace** [comment]
@montekaka CORS error is very common issues. Using the [rack-cors gem](https://github.com/cyu/rack-cors) may solve the problem.

**Comment by montekaka** [comment]
> @montekaka CORS error is very common issues. Using the [rack-cors gem](https://github.com/cyu/rack-cors) may solve the problem.

Thanks so much for the quick response.  I setup it as well. I have cors.rb: 

```
Rails.application.config.middleware.insert_before 0, Rack::Cors do
  allow do
    origins '*'
    resource '*',
    headers: :any,
    expose: ['access-token', 'expiry', 'token-type', 'uid', 'client'],
    methods: [:get, :post, :put, :patch, :delete, :options, :head]
  end
end
```

**Comment by montekaka** [comment]
I might have my issue solved by change the withCredentials to false.

**Comment by fkapsahili** [comment]
I actually had to add `credentials: true` to the cors.rb initializer:
```ruby
resource "*",
   headers: :any,
   methods: :any,
   credentials: true
