### ISSUE TITLE
What doest ahoy.js able to do without cookies

### ISSUE THREAD

**Issue by nicolas-brousse** [ankane/ahoy.js#40]
We install `ahoy` gem and `ahoy.js` on a project today to use it. So I'm looking on configuration to know how it works depending of some configs.  

And I would like to know if `ahoy.js` do something if `cookies` is set to `false`. From my code reading it looks like not. But I would like to be sure.

**Comment by ankane** [comment]
Hey @nicolas-brousse, I'm not sure I understand the question, but you should be able to try it without cookies and see how it behaves.
