### ISSUE TITLE
FYI: ahoy/events routes are now blocked by EasyPrivacy block list

### ISSUE THREAD

**Issue by zealot128** [ankane/ahoy.js#43]
Just noticed when testing some analytics locally, the beacon did not fire.

https://github.com/easylist/easylist/blob/master/easyprivacy/easyprivacy_general.txt#L487

Seems to be, it was added 13 days ago.

To make analytics still work, if that is desired, then one needs to change the path:

```
# config/initializers/ahoy.js
Ahoy.api = false

# config/routes.rb
 mount Ahoy::Engine => "/ahoyyy"

# app/.../ahoy.js
 ahoy.configure({
    visitsUrl: "/ahoyyy/visits",
    eventsUrl: "/ahoyyy/events",
  })
```

**Comment by ankane** [comment]
Hey @zealot128, thanks for sharing. It's unfortunate that tracking user activity on your own website is being grouped together with Google and Facebook tracking users across the Internet.

**Comment by davidalejandroaguilar** [comment]
@zealot128 I think you meant:

```rb
# config/initializers/ahoy.rb
Ahoy.api = true
```

Since this is what [will mount the route](https://github.com/ankane/ahoy/blob/926cc8390f2a6e42e894aad5ae881d5706aafd64/config/routes.rb#L2) for JS tracking to use.

**Comment by zealot128** [comment]
> @zealot128 I think you meant:
> 
> ```ruby
> # config/initializers/ahoy.rb
> Ahoy.api = true
> ```
> 
> Since this is what [will mount the route](https://github.com/ankane/ahoy/blob/926cc8390f2a6e42e894aad5ae881d5706aafd64/config/routes.rb#L2) for JS tracking to use.

No, it's correct that way that I wrote.
In the code snippt from you, you can see that Ahoy will be automatically mounted at the standard location. As the tickets description, the standard location at "/ahoy" is blocked by Adblock-Lists. So we disable the automatic mounting by setting it to false and **manually** mount it to a different location.

**Comment by davidalejandroaguilar** [comment]
Ahh got it, thanks for the additional explanation.
