### ISSUE TITLE
ahoy.track() - no implicit conversion of Array into String

### ISSUE THREAD

**Issue by SarahJaanuu** [ankane/ahoy.js#46]
Ahoy is working correctly 99% of the time, but once in a while we are getting "no implicit conversion of Array into String" errors 

Instead of `{"name": "My Name", "properties": { ... }}` it is posting that wrapped as an array (`[{"name": "My Name", "properties": { ... }}]`) to /ahoy/events

We have seen occurrences on windows and mac, chrome and firefox. 
It seems like every pageview of an affected user will trigger the error.

**Comment by ankane** [comment]
Hi @SarahJaanuu, thanks for reporting. It sounds like there could a timing issue where the event queue gets corrupted, but I'm not able to reproduce or see exactly how.

**Comment by SarahJaanuu** [comment]
Thanks for the response @ankane . any top of mind ideas how to fix? I haven't been able to personally reproduce either, just seeing it in the logs. It seems quite rare - ~50 occurrences to 8 unique users out of 700,000 events

**Comment by ankane** [comment]
It'll be hard to fix without knowing how to reproduce. It could also be a browser extension interfering. With those numbers, I personally wouldn't worry about it. However, if you find anything, please let me know.

**Comment by ankane** [comment]
Cleaning up stale issues
