### ISSUE TITLE
Events that occurred on different days have the same visit token

### ISSUE THREAD

**Issue by ACPK** [ankane/ahoy.js#47]
We noticed that ahoy_events on different days have the same visit_id which are attributed to ahoy_visits.  

Based on the text from the Readme, wouldn't events have different visit IDs if it's been over four hours?

**Readme:** 

```The visit token expires after 4 hours, in which a new visit is created. Visits are useful for tracking metrics like monthly active users. The visitor token expires after 2 years. ```.

On a side note, we have some ahoy_event records from last month that have the same visit_id as records created today. How are vistors being tracked since we have no users accounts (the site doesn't have a login function), set mask_ips to True, and set cookies to False?

**Comment by ACPK** [comment]
@ankane - Any suggested would be greatly appreciated!

**Comment by ankane** [comment]
Hey @ACPK, if you use this with the Ruby gem and cookies, visits expire after 4 hours of inactivity, as the server refreshes them: https://github.com/ankane/ahoy#visit-duration

If you use this without cookies, visits last indefinitely.
