### ISSUE TITLE
Create option to configure visitTtl and visitorTtl

### ISSUE THREAD

**Issue by thejullius** [ankane/ahoy.js#49]
Hello, our team uses your lib and we had some difficulties with the default value of `visitTtl` and `visitorTtl`, mainly because of `visitTtl`.

Basically, our session token expires in thirty days, while the `ahoy_visit` cookie expires in four hours. After four hours, the `ahoy_visit` cookie is renewed and our backend loses control of the events because a new `visit_token` is created.

Our suggestion is to keep the default valves, but create a option to configure these values on the `configure` function.

I will send a PR with the code change and, if it makes sense, let me know and I will update the documentation as well.

**Comment by lsantosc** [comment]
👍

**Comment by marciovsena** [comment]
@ankane any predictions for when this pull-request will be merged?
