### ISSUE TITLE
visitParams is not sending with trackView

### ISSUE THREAD

**Issue by bbugh** [ankane/ahoy.js#51]
Hello again open source hero, ankane. 💪 

Our `visitParams` is not sending with `trackView`. I followed the instructions in the Ruby ahoy repository and dug through the code, but I can't tell why this isn't working, and there's no documentation to explain it that I can see.

Using the example from the Ruby repository in our Vue router:

```javascript
router.afterEach(route => {
  // we want to send some extra stuff here
  ahoy.configure({ visitParams: { referralCode: 123 } })
  ahoy.trackView()
})
```

Nothing in `visitParams` appears in the payload.

**Comment by ankane** [comment]
Hey @bbugh, `visitParams` are only sent with `trackVisit`. You can pass additional properties to page views with `trackView(additionalProperties)`.

**Comment by bbugh** [comment]
Ah... so you can! Thank you for the info, sorry for dead end report!
