### ISSUE TITLE
ahoy.js does not track click events for a-tags that contain HTML tags. Is it intentional?

### ISSUE THREAD

**Issue by ts-3156** [ankane/ahoy.js#57]
As far as I investigate, there are differences in behavior as follows. I want to track click events in all a-tags, is there a way to do that?

```html
# Click events are tracked
<a>click</a>

# Click events are not tracked
<a><span>click</span></a>
```

**Comment by ankane** [comment]
Hey @ts-3156, this was merged an hour ago if you use master: https://github.com/ankane/ahoy.js/pull/54.

**Comment by ts-3156** [comment]
Thanks you your answer!

**Comment by ts-3156** [comment]
@ankane When do you plan to release the new version? I can't make up my mind if I should use the master branch or wait for a new release.
