### ISSUE TITLE
Click event is duplicated when redirect from A.html to B.html

### ISSUE THREAD

**Issue by nguyenvanthuan0501** [ankane/ahoy.js#58]
I'm a fresher.  I'm having problem using __Ahoy.js__.
I have 2 sample file HTML include Ahoy.js.
Sample A:

    <a href="B.html"> <img src='a.jpg'> </a>

Sample B:

    <button>Add Cart</button>

I click __a tag__, when redirect to __'B.html'__, maybe eventQueue is still saved from __A.html__, so it should be duplicated event when send request via Ajax.

Can anyone help me??
Thanks you!.

**Comment by ankane** [comment]
Hey @nguyenvanthuan0501, that's possible if `useBeacon: false` is set (to make sure events are delivered at least once). Each event should have a unique id, so if you really need to avoid duplication, you'll probably want to add some logic server-side to prevent it.

**Comment by longvovan** [comment]
> Hey @nguyenvanthuan0501, that's possible if `useBeacon: false` is set (to make sure events are delivered at least once). Each event should have a unique id, so if you really need to avoid duplication, you'll probably want to add some logic server-side to prevent it.

@ankane I also have a problem like above, solution you reply issue not working for me. Have you other solutions?
