### ISSUE TITLE
Add the option to keep the ahoy_visit cookie alive

### ISSUE THREAD

**Issue by kevinjqiu** [ankane/ahoy.js#59]
Currently, the ahoy_visit cookie is only renewed if a server API is called, which the `AhoyController` on the server side extends the `ahoy_visit` cookie's expiration date.

This becomes problematic when the user stays idle the page, but whose actions should still be considered to belong to the same ahoy visit when they resume.

Could we have an option in ahoy to start a timer that automatically extends the `ahoy_visit` cookie's expiration date?

**Comment by kevinjqiu** [comment]
@ankane Any thoughts on this? Happy to contribute a PR if this sounds reasonable. Thanks!

**Comment by ankane** [comment]
Hey @kevinjqiu, thanks for the suggestion. I'm not sure this is common enough to officially support, but you can probably fork and add it.
