### ISSUE TITLE
Why visitsUrl and eventsUrl should use double // on my side 

### ISSUE THREAD

**Issue by bukandicki** [ankane/ahoy.js#61]
Hi @ankane,
i'm using your amazing ahoy.js

It doesn't seem like a problem, but just to be sure. Is this a bug or should it be like this? So i tried to configure my ahoy.js like this

```
ahoy.configure({
  urlPrefix: process.env.VUE_APP_BASE_API,
  visitsUrl: "//ahoy/visits",
  eventsUrl: "//ahoy/events",
  page: "landing-page",
  platform: "Web",
  useBeacon: true,
  startOnReady: true,
  trackVisits: true,
  cookies: true,
  cookieDomain: null,
  headers: {},
  visitParams: {},
  withCredentials: true,
  visitDuration: 4 * 60, // 4 hours
  visitorDuration: 2 * 365 * 24 * 60 // 2 years
})
```

on `visitsUrl` and `eventsUrl` should always use double `//` if I use single `/` it doesn't send any action to the backend. and by the way my env variable contains something like this `http://localhost:3000`

can you clarify to help me? Thanks in advance

**Comment by ankane** [comment]
Hey @bukandicki, not sure why that'd be the case, and not really sure how to reproduce.
