### ISSUE TITLE
Update the no-jquery branch

### ISSUE THREAD

**Issue by Startouf** [ankane/ahoy.js#62]
Hello,
We have a React frontend app that relies on the no-jquery branch of your gem which is a bit outdated now (and we have problems with duplication of cookies with httpOnly/sameSite, etc). Do you plan on maintaining it or should we drop it to use something else ?

**Comment by ankane** [comment]
Hey @Startouf, jQuery was removed as a dependency in the 0.3.0 release. In general, branches aren't maintained (you'll need to do it yourself).
