### ISSUE TITLE
Add debug messaging around sendbeacon

### ISSUE THREAD

**Issue by wenqige** [ankane/ahoy.js#65]
In reference to https://github.com/ankane/ahoy.js/issues/64

This issue is currently causing a lot of TypeError: Illegal Invocation error metrics. I don't think it will be very easy to provide a way to reproduce but would it be possible to improving the visibility into the circumstances surrounding the exceptions being thrown? The error it self doesn't give very much info on why it's taking place. Would it be possible to add a try catch to give useful debug output and rethrow, such as an output of eventsUrl() and data and index_module_1's return in order to help us with debugging the Illegal Invocations?

**Comment by ankane** [comment]
Hey @wenqige, you can fork and try that, but I'm not sure it'll provide any more info than the exception itself. It could be related to one of these issues:

- https://github.com/vercel/next.js/issues/23856
- https://github.com/miguelmota/Navigator.sendBeacon/issues/8
