### ISSUE TITLE
Why did you remove #trackAll ? (just curious)

### ISSUE THREAD

**Issue by ts-3156** [ankane/ahoy.js#67]
Thanks for the useful gem!

Why did you remove #trackAll in the latest ahoy.js? (just curious)

One more question. Why did you stop mentioning ahoy.js on [ankane/ahoy/README.md](https://github.com/ankane/ahoy)?

**Comment by ankane** [comment]
Hey @ts-3156, `trackAll` was removed to encourage developers to be more thoughtful about tracking.

I'm not sure I follow the last question - there are many references to Ahoy.js in the current Ahoy readme.

**Comment by ts-3156** [comment]
@ankane Thanks for the answer.

> there are many references to Ahoy.js in the current Ahoy readme.

You are right. I was wrong. Sorry.

Have a nice day!
