### ISSUE TITLE
Next js and ahoy

### ISSUE THREAD

**Issue by DonikaV** [ankane/ahoy.js#77]
Hello, i am getting issues with ahoy, I am including ahoy.js in the DOM. And when it is loaded and app is loaded I am doing 

ahoy.configure(config) // my configuration
then I do 
```
ahoy.trackView();
ahoy.trackClicks("a, button, input[type=submit]");
ahoy.trackSubmits("form");
ahoy.trackChanges("input, textarea, select");
```
But first POST requests goes to wrong URL (the default ones from ahoy.js) and I am getting 404. Can I avoid this somehow?

**Comment by ankane** [comment]
Hi @DonikaV, it sounds like `configure` is being called after the other methods.
