### ISSUE TITLE
Expo Support?

### ISSUE THREAD

**Issue by adenta** [ankane/ahoy.js#79]
I see there is dedicated iOS and Android support. When I tried importing `ahoy.js` into a react native/expo project, I was unable to get the library working.
![IMG_4607](https://github.com/ankane/ahoy.js/assets/9259638/ac2fa2f8-3c4b-4771-985c-a9817cb3e7c0)

Will do some research and report back, I couldn't find anyone trying something similar online.

**Comment by adenta** [comment]
It looks like [this](https://github.com/ankane/ahoy.js/blob/master/src/index.js) is a single file, so wouldn't be impossible to remove the references to `document` by hand, replacing with react-native/expo alternatives.

Unsure right now if that would make this a seperate `ahoy-expo.js` library or configuration on top of this library

**Comment by ankane** [comment]
Hi @adenta, thanks for sharing. I think it's probably better as a separate library.
