### ISSUE TITLE
Using useBeacon: true results in NS_ERROR_FAILURES on events

### ISSUE THREAD

**Issue by SabracNL** [ankane/ahoy.js#81]
When using the config useBeacon: true, the events tracking (clicks / views and submits) result in an NS_ERROR_FAILURE for beacon.

Disabling this config fixes the issue.

I've tried digging further into the code to find the cause, but was unable to do so.

```
window.navigator.sendBeacon(eventsUrl(), serialize(data));
```

Seems to be the culprit in the trackEventNow() function

**Comment by ankane** [comment]
Hi @SabracNL, this doesn't seem like an issue with Ahoy.js.
