### ISSUE TITLE
Issue with SSR: window is not defined

### ISSUE THREAD

**Issue by gbudiman** [ankane/ahoy.js#86]
First of all, I know there's a workaround https://github.com/ankane/ahoy.js/issues/35
But it's a workaround -- we still need to do `dynamic` import, which is not ideal because we lose the benefits of React Server Component (RSC).

**I'm happy to open a PR** to address this issue permanently - but since I'm not familiar with `ahoy.js`'s architecture, I would like to consult people who are familiar with it.

The core issue is that `window` object, in SSR-centric environment like Next.js, is _not_ always defined. RSC generation runs on the server - where `window` object is undefined. I hope I'm not oversimplifying this, but the solution is to do `if (typeof window === 'undefined') return` such that `ahoy` doesn't run server-side. Would this solution be viable?

Thanks

**Comment by ankane** [comment]
Hi @gbudiman, it's not something I'd like to support, but you could fork the library to support it.
