### ISSUE TITLE
ahoy.configure is ignored?

### ISSUE THREAD

**Issue by creativereason** [ankane/ahoy.js#9]
So I have code that is calling ahoy from a Wordpress front-end to post to a Rails backend (part of the site is dynamically served from rails APIs). 

I have ahoy.configure set as such (my API's run from /flip). 

```
    ahoy.configure({
      urlPrefix: "",
      visitsUrl: "/flip/ahoy/visits",
      eventsUrl: "/flip/ahoy/events",
      cookieDomain: null,
      page: null,
      platform: "Web",
      useBeacon: false,
      startOnReady: true
    });  

```

Sometimes, I see it working and events are being added to the database, but for click events I'm getting 404 errors where it is trying to find the events at `<domain>/ahoy/events`. 

Where and when should configure be called? Is it enough to call it on `document.load`?

**Comment by ankane** [comment]
You'll need to call it before document.load fires, or set startOnReady to false and call ahoy.start() manually.

**Comment by dts** [comment]
From my reading of the code, the only way to do this is to set ahoy to the configuration, which is made possible by line 36:

```
ahoy = { ...config }
// load ahoy.js
ahoy.start()
```

If you configure after you load the script, you won't actually be able to control startOnReady and various cookie parameters.

**Comment by ankane** [comment]
You should be able to call configure after the JS is loaded but before jQuery's ready event fires.

**Comment by dts** [comment]
If I'm not mistaken, unless y set startOnReady to false before you load `ahoy.js`, it will still call start() on `ready`.

**Comment by ankane** [comment]
Looks like a bug. Feel free to submit a PR, or I'll tackle it when I can.

**Comment by dts** [comment]
That was fast ;).  Thanks!
